---
ghq_root: "{{ ansible_user_dir }}/ghq/github.com"
zsh_completion_dir: "{{ ansible_user_dir }}/.zsh/completions"

git_repositories:
  - { repo: "https://github.com/kowwwwji/dotfiles.git", dest: "{{ ghq_root }}/kowwwwji/dotfiles" }

symlinks:
  - { src: "{{ ansible_user_dir }}/.vim", dest: "{{ ansible_user_dir }}/.config/nvim/vim" }
  - { src: "{{ ansible_user_dir }}/.vimrc", dest: "{{ ansible_user_dir }}/.config/nvim/init.vim" }

setup_repositories:
  - { chdir: "{{ ansible_user_dir }}/ghq/github.com/kowwwwji/dotfiles", creates: "{{ ansible_user_dir }}/.vimrc" }
